#!/bin/sh
# python3 startup.py
# i3-save-tree --workspace 2 > $HOME/.config/i3/workspace-2.json

# i3-msg "workspace 1; append_layout $HOME/.config/i3/workspace-1.json"
# i3-msg "workspace 2; append_layout $HOME/.config/i3/workspace-2.json"

i3-msg "workspace 1"
i3-msg "exec --no-startup-id firefox"
i3-msg "exec --no-startup-id subl"
i3-msg "exec --no-startup-id discord"
i3-msg "exec --no-startup-id spotify-adblock"
i3-msg "exec --no-startup-id $HOME/.config/polybar/launch.sh"

# BACKGROUND
i3-msg "exec --no-startup-id feh --randomize --bg-fill /media/data/GFX/Unsplash"
